# Generated by Django 5.1.6 on 2025-08-13 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dete', models.DateTimeField(auto_created=True, verbose_name='تاریخ ایجاد ')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='شماره تلفن')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('type', models.ImageField(choices=[(1, 'superuser'), (2, 'admin'), (3, 'customer')], default=3, upload_to='', verbose_name='نقش کاربر')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name=' تاریخ بروز رسانی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dete', models.DateTimeField(auto_created=True, verbose_name='تاریخ ایجاد ')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام ')),
                ('last_name', models.CharField(max_length=50, verbose_name=' نام خانوداگی ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='تصویر پروفایل')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name=' تاریخ بروز رسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
