# Generated by Django 5.1.6 on 2025-08-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=' تاریخ بروز رسانی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_dete',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد '),
        ),
    ]
