# Generated by Django 5.1.6 on 2025-09-10 21:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_update_date_alter_user_created_dete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, null=True, verbose_name='توکن')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با 09 شروع شده و 11 رقم باشد', regex='^09\\d{9}$')], verbose_name='شماره تلفن')),
                ('code', models.SmallIntegerField(verbose_name='کد یکبار مصرف')),
                ('code_expiry', models.DateTimeField(default=datetime.datetime(2025, 9, 10, 21, 8, 43, 959711, tzinfo=datetime.timezone.utc), verbose_name='تاریخ انقضای کد')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده؟')),
            ],
            options={
                'verbose_name': 'رمز یکبار مصرف',
                'verbose_name_plural': ' احراز هویت Otp',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'مدیریت پروفایل ها '},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'مدیریت کاربران '},
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_dete',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name=' تاریخ بروز رسانی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'superuser'), (2, 'admin'), (3, 'customer')], default=3, verbose_name='نقش کاربر'),
        ),
    ]
